### ISSUE TITLE
ESP32 : memory leak ?

### ISSUE THREAD

**Issue by ghost** [gmag11/NtpClient#111] opened 2020-07-06 23:15 UTC
Hi,

I've compiled your official example for ESP32 on a board LOLIN ESP32 PRO.

In order to compile it, I've patched the NtpClientLib.cpp as discuted in another thread.
Line 289 replaced by
if (ntpServerIPAddress == INADDR_NONE) {

Decrease in free heap seems to occur with each NTP request.

8 00:55:37 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:00:45 since 00:54:53 07/07/2020
Free heap: 260916
9 00:55:42 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:00:50 since 00:54:53 07/07/2020
Free heap: 260916
10 00:55:47 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:00:55 since 00:54:53 07/07/2020
Free heap: 260916
11 00:55:52 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:00 since 00:54:53 07/07/2020
Free heap: 260916
12 00:55:57 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:05 since 00:54:53 07/07/2020
Free heap: 260628
NTP request Sent
Got NTP time: 00:55:58 07/07/2020
13 00:56:02 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:10 since 00:54:53 07/07/2020
Free heap: 259172
14 00:56:07 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:15 since 00:54:53 07/07/2020
Free heap: 259172
15 00:56:12 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:20 since 00:54:53 07/07/2020
Free heap: 259172
16 00:56:17 07/07/2020 Summer Time. WiFi is connected. Uptime:    0 days 00:01:25 since 00:54:53 07/07/2020
Free heap: 259172

Thanks for all the hard work on this stuff.

**Comment by illosan** [comment] 2020-09-09 07:09
I confirm, every NTP request the esp32 loses 1760 bytes of free heap...

**Comment by gmag11** [comment] 2020-11-26 10:53
You are right. This seems to be caused by ESP32 AsyncUDP class. I've created a new library that uses internal LWIP functions both on ESP8266 and ESP32, so I get rid of external libraries. You can find it on https://github.com/gmag11/ESPNtpClient

**Comment by gmag11** [comment] 2021-03-09 08:32
I close this issue. Feel free to reopen it if you have additional info

**Closed as completed by gmag11** 2021-03-09 08:32 UTC

**Comment by laboratoryyingong** [comment] 2022-08-22 02:36
> I confirm, every NTP request the esp32 loses 1760 bytes of free heap...

That's correct, I found that also. And it is difficult for me to narrow down with this lib.

**Comment by gmag11** [comment] 2022-08-22 15:00
I keep this library for compatibility. But for some time ago it is not the best way to synchronize time. You should use internal esp32 functions. Check this tutorial https://randomnerdtutorials.com/esp32-ntp-timezones-daylight-saving/

This works with esp8266 too.

**Comment by laboratoryyingong** [comment] 2022-08-24 12:30
> I keep this library for compatibility. But for some time ago it is not the best way to synchronize time. You should use internal esp32 functions. Check this tutorial https://randomnerdtutorials.com/esp32-ntp-timezones-daylight-saving/
> 
> 
> 
> This works with esp8266 too.

Thanks for your reply and contribution. I am reading your code and try to figure out. Hope I could solve this issue. Thanks again for your help!
