### ISSUE TITLE
ESP8266 Example sketch stops working 

### ISSUE THREAD

**Issue by raihei** [gmag11/NtpClient#64] opened 2018-04-02 13:48 UTC
Hello,

as soon as I comment out the following lines in the loop, the example is not working anymore. 

```	
/*if ((millis() - last) > 5100) {
		//Serial.println(millis() - last);
		last = millis();
		Serial.print(i); Serial.print(" ");
		Serial.print(NTP.getTimeDateString()); Serial.print(" ");
		Serial.print(NTP.isSummerTime() ? "Summer Time. " : "Winter Time. ");
		Serial.print("WiFi is ");
		Serial.print(WiFi.isConnected() ? "connected" : "not connected"); Serial.print(". ");
		Serial.print("Uptime: ");
		Serial.print(NTP.getUptimeString()); Serial.print(" since ");
		Serial.println(NTP.getTimeDateString(NTP.getFirstSync()).c_str());

		i++;
	}*/
delay(500);
```

I changed the delay to 500 but it still works when the lines above are not commented out. From what I can see, these lines should not be needed,  because NTP.begin & NTP.setInterval should be enough, right?

Here is the complete code (pretty much the unchanged example code)
```
#include <TimeLib.h>
#include "WifiConfig.h"
#include <NtpClientLib.h>
#include <ESP8266WiFi.h>

#ifndef WIFI_CONFIG_H
#define YOUR_WIFI_SSID ""
#define YOUR_WIFI_PASSWD ""
#endif // !WIFI_CONFIG_H

#define ONBOARDLED 2 // Built in LED on ESP-12/ESP-07

int8_t timeZone = 1;

// Start NTP only after IP network is connected
void onSTAGotIP(WiFiEventStationModeGotIP ipInfo) {
	Serial.printf("Got IP: %s\r\n", ipInfo.ip.toString().c_str());
	NTP.begin("pool.ntp.org", timeZone, true);
	NTP.setInterval(63);
	digitalWrite(ONBOARDLED, LOW); // Turn on LED
}

// Manage network disconnection
void onSTADisconnected(WiFiEventStationModeDisconnected event_info) {
	Serial.printf("Disconnected from SSID: %s\n", event_info.ssid.c_str());
	Serial.printf("Reason: %d\n", event_info.reason);
	digitalWrite(ONBOARDLED, HIGH); // Turn off LED
	//NTP.stop(); // NTP sync can be disabled to avoid sync errors
}

void processSyncEvent(NTPSyncEvent_t ntpEvent) {
	if (ntpEvent) {
		Serial.print("Time Sync error: ");
		if (ntpEvent == noResponse)
			Serial.println("NTP server not reachable");
		else if (ntpEvent == invalidAddress)
			Serial.println("Invalid NTP server address");
	}
	else {
		Serial.print("Got NTP time: ");
		Serial.println(NTP.getTimeDateString(NTP.getLastNTPSync()));
	}
}

boolean syncEventTriggered = false; // True if a time even has been triggered
NTPSyncEvent_t ntpEvent; // Last triggered event

void setup()
{	
	static WiFiEventHandler e1, e2;

	Serial.begin(115200);
    Serial.println();
	WiFi.mode(WIFI_STA);
	WiFi.begin(YOUR_WIFI_SSID, YOUR_WIFI_PASSWD);
	
	pinMode(ONBOARDLED, OUTPUT); // Onboard LED
	digitalWrite(ONBOARDLED, HIGH); // Switch off LED

	NTP.onNTPSyncEvent([](NTPSyncEvent_t event) {
		ntpEvent = event;
		syncEventTriggered = true;
	});

	// Deprecated
	/*WiFi.onEvent([](WiFiEvent_t e) {
		Serial.printf("Event wifi -----> %d\n", e);
	});*/

	e1 = WiFi.onStationModeGotIP(onSTAGotIP);// As soon WiFi is connected, start NTP Client
	e2 = WiFi.onStationModeDisconnected(onSTADisconnected);

}

void loop()
{
	static int i = 0;
	static int last = 0;

	if (syncEventTriggered) {
		processSyncEvent(ntpEvent);
		syncEventTriggered = false;
	}

	/*if ((millis() - last) > 5100) {
		//Serial.println(millis() - last);
		last = millis();
		Serial.print(i); Serial.print(" ");
		Serial.print(NTP.getTimeDateString()); Serial.print(" ");
		Serial.print(NTP.isSummerTime() ? "Summer Time. " : "Winter Time. ");
		Serial.print("WiFi is ");
		Serial.print(WiFi.isConnected() ? "connected" : "not connected"); Serial.print(". ");
		Serial.print("Uptime: ");
		Serial.print(NTP.getUptimeString()); Serial.print(" since ");
		Serial.println(NTP.getTimeDateString(NTP.getFirstSync()).c_str());

		i++;
	}*/
	delay(500);
}
```

and here is the serial output:
```
Got IP: 172.17.17.90
Time Sync error: NTP server not reachable
```
Somehow the first Sync is always failing, but then it stops completely, no new Sync is tried. When the lines are not commented out, the first sync is also failing, but then quickly the next sync is started and is successful.

NtpClientLib 2.0.5
esp8266 2.4.0
Arduino IDE 1.6.9

regards
raihei

**Comment by raihei** [comment] 2018-04-02 13:49
I have no idea, why the code tags are not working correctly...

**Comment by raihei** [comment] 2018-04-08 11:59
Here is the output with NTP Debug enabled:

```
Got IP: 172.17.17.90
NTP server 0 set to: pool.ntp.org 
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
-- NTP error :-(
NTP time zone set to: 1, result: OK
--Set daylight ON
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
-- NTP error :-(
Short sync interval set to 5
Long sync interval set to 1800
Time sync started
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
-- NTP error :-(
Long sync interval set to 63
Time Sync error: NTP server not reachable
```

and here with WIFI debug and NTP debug enabled:

```
connected with TESTWIFI, channel 6
dhcp client start...
wifi evt: 0
ip:172.17.17.90,mask:255.255.255.0,gw:172.17.17.1
wifi evt: 3
Got IP: 172.17.17.90
NTP server 0 set to: pool.ntp.org 
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
NTP time zone set to: 1, result: OK
--Set daylight ON
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
Short sync interval set to 5
Long sync interval set to 1800
Time sync started
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
Long sync interval set to 63
Time Sync error: NTP server not reachable
```

Could the "please start sntp first !" be the cause of the problem?

**Comment by raihei** [comment] 2018-04-08 12:06
Ok, when the lines in the first post are not commented out, I still get the "please start sntp first!" messages. But then it works...

```
connected with TESTWIFI, channel 6
dhcp client start...
wifi evt: 0
ip:172.17.17.90,mask:255.255.255.0,gw:172.17.17.1
wifi evt: 3
Got IP: 172.17.17.90
NTP server 0 set to: pool.ntp.org 
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
NTP time zone set to: 1, result: OK
--Set daylight ON
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
Short sync interval set to 5
Long sync interval set to 1800
Time sync started
-- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
please start sntp first !
-- NTP error :-(
Long sync interval set to 63
Time Sync error: NTP server not reachable
1 -- NTP Server hostname: pool.ntp.org
-- Transmit NTP Request
Sync frequency set low
Summer Time
First sync! 14:04:07 08/04/2018
Succeccful NTP sync at 14:04:07 08/04/2018
14:04:07 08/04/2018 Summer Time. WiFi is connected. Uptime: 0 days 00:00:25 since 14:04:07 08/04/2018
Got NTP time: 14:04:07 08/04/2018
```

**Comment by SpoonS2K** [comment] 2018-04-21 08:02
I have the same kind of problem. I have to add a dummy String polling `getTimeDateString()` in my loop to get `setInterval` to work. Without this String, first sync to the NTP server is ok but after it stops working

**Comment by raihei** [comment] 2018-05-04 21:51
Thanks for this tip, that works for me too!

**Comment by reivaxy** [comment] 2018-05-15 14:51
Not using the example, I have the same problem when trying to use onNTPSyncEvent.
No event is fired ever if calling only NTP.begin();

If I add NTP.getTimeStr() in my loop(), an event is fired when sync occurs (15 seconds after IP is obtained from wifi network)

**Comment by reivaxy** [comment] 2018-05-15 15:37
I have done some digging/debugging, and the "issue" is with the Time library usage.
It needs to be refreshed periodically so that the sync callback can be called. The sync callback here is the NTP server call.
So, just adding a call to now() in the loop() will solve the issue.

**Comment by raihei** [comment] 2018-05-18 14:24
Thanks for looking into that issue!

**Comment by gmag11** [comment] 2018-05-21 09:46
I am not able to reproduce this. I've tried several delay times and I always get something like:
```
Got IP: 192.168.1.95
Connected: yes
Got NTP time: 11:42:46 21/05/2018
```
Anyway @reivaxy is right, as Time library is based on `millis()` counter, it needs to be refreshed to update time internally and avoid counter overflow.

**Comment by raihei** [comment] 2018-05-21 12:50
The delay time has nothing do to with it, as I pointed out in the first post. I just mentioned it for completeness.

**Comment by gmag11** [comment] 2018-05-23 15:41
Now I understand what happens. Time library is the responsible to trigger time sync. The logic that decides it is time for a new sync is inside `now ()` function. So if there isn't any call to it NTPClient will never get a request to start a NTP sync. It is the way it is. I am not the developer of Time library.
What you need is calling `now()` from time to time. It does not need to be quite often.

Another workaround is to trigger NTP sync from your code, calling `setTime (getTime ())`. This will always generate a NTP call and update time inside TimeLib.

If you confirm this is the root cause I will close this issue.

**Comment by gmag11** [comment] 2018-07-23 18:45
I come back here because I've done the simple example that I promised 😃 . You can find it [here](https://github.com/gmag11/NtpClient/tree/master/examples/NTPClientBasic)

**Closed as completed** 2018-07-23 20:16 UTC
Labels: help wanted

**Comment by macmeck** [comment] 2019-10-27 20:22
This might be worth mentioning in the example files. It took me quite some time to identify the implicit call to `now()`...

**Comment by hoekbrwr** [comment] 2022-08-09 10:44
Somehow the problem is back again. I tried your simple example and show us too and it is never updated! I have set the interval to 30 sec and did an extra call to getTimeDateString().
