### ISSUE TITLE
Year 2036

### ISSUE THREAD

**Issue by MarcFinns** [gmag11/NtpClient#74] opened 2018-09-28 21:39 UTC
Hello, i had noticed that sporadically i would get a date in year 2036. I normally use ntp.org or google as servers.
Today i tried to point the device to the NTP server of my Synology diskstation and i get ONLY year 2036! Some bugs around? let me know if you need any specific test, happy to help...
thanks!

**Comment by JosefKuchar** [comment] 2018-10-27 08:36
Duplicate of #70

**Closed as completed** 2019-01-04 19:42 UTC
