### ISSUE TITLE
NTP sync returns random day and time for the year 2036

### ISSUE THREAD

**Issue by Uup115** [gmag11/NtpClient#70] opened 2018-07-31 15:33 UTC
Hello,

First of all...  Great library!

I began using your library last week.  Sometimes the NTP sync will return a date in the year 2036.  Any thoughts as to why?

Best Regards,
Aaron

**Comment by rayvt** [comment] 2018-09-02 17:28
Yes, agreed, great library.

I also am sometimes getting bogus dates in 2036.  For example:
00:28:16 02/07/2036 Winter Time. 
Unix timestamp: 2085956896

I suspect there is an NTP server that is sending bad timestamps.  Normal NTP will work okay because it will discard outliers.  It is a problem here, because we do not cross-check or validate.

I am looking to see if I can come up with a small/simple way to avoid this.

**Comment by foxygnu** [comment] 2018-09-25 19:30
Hello,

Same problem here. But i can't figure when that appends. The bug was not present some time in past ...

Anyway :

NTP server set to ntp.local
NTP time zone set to: 1
--Set daylight saving ON
Starting UDP
UDP port: 123
-- Receive NTP Response
Summer Time
Sync frequency set low
Successful NTP sync at 21:18:42 25/09/2018
Got NTP time: 21:18:42 25/09/2018
Short sync interval set to 15
Long sync interval set to 1800
Time sync started
Starting UDP
UDP port: 123
-- Receive NTP Response
Winter Time
Sync frequency set low
Successful NTP sync at 07:28:16 07/02/2036
Got NTP time: 07:28:16 07/02/2036
NTP client initialized

That's always the same date & time ... strange !

And => https://github.com/esp8266/Arduino/blob/master/tools/sdk/lwip/src/core/sntp.c

Read this :

/**
 * SNTP packet format (without optional fields)
 * Timestamps are coded as 64 bits:
 * - 32 bits seconds since Jan 01, 1970, 00:00
 * - 32 bits seconds fraction (0-padded)
 * For future use, if the MSB in the seconds part is set, seconds are based
 * on Feb 07, 2036, 06:28:16.
 */

See ? 07/02/2036 06:28:16 (+1h for timezone) ? :)

I think there is a problem of parsing sntp or an incompatibility between the esp sdk and the ntpclientlib ...

What is your interpretation of this ?

PS: i use a local NTP for debug purpose and i can assure you this is not a ntp server problem here.

**Comment by darkcheater** [comment] 2018-10-27 07:03
I have the same problem..

**Comment by JosefKuchar** [comment] 2018-10-27 08:36
Yes it's 7:28 for me and it's pretty irritating

**Comment by MarcFinns** [comment] 2018-10-27 09:16
I have it when WiFi coverase is poor

**Comment by TomsCircuits** [comment] 2018-10-27 12:18
I do have the same problem. Research shows that the time/date 07:28:16 07/02/2036 is the NTP roll-over date. The time stamp in NTP is given in seconds, starting from 1.1.1900 (UNIX starts 1.1.1970).

If you start with 0xFFFFFFFF as an NTP time stamp and subtract the 70 years of offset in seconds, and then convert this to time/date you get 07-Feb-36 06:28:15 UTC. So the packet must have contained a time stamp of 0xFFFFFFFF or possibly 0. The library does not check for this at the moment (and it shouldn't have to).

**Comment by TomsCircuits** [comment] 2018-10-27 13:18
OK, I think this becomes clearer. I added a print statement for the NTP timestamp after decoding of the UDP packet. Here is the result:

```
Connected to XXXXXXXX
Got IP: 192.168.0.40
Connected: yes
Secs: 3749634515
Secs: 0
Got NTP time: 07:28:16 07/02/2036
Time Sync error: NTP server not reachable
Secs: 3749634535
Got NTP time: 15:08:55 27/10/2018
Secs: 3749634541
Got NTP time: 15:09:01 27/10/2018
Secs: 3749634547
Got NTP time: 15:09:07 27/10/2018
```
Looks like I do get a valid packet first. The second packet seems to be corrupt. And then the server isn't there anymore...

**Comment by TomsCircuits** [comment] 2018-10-27 13:52
I think I am starting to understand. There is a method called getTime. This method requests a NTP message from an NTP server and returns the new time.

But if there is a timeout, it raises a noResponse ntpEvent and then it returns 0; This 0 then gets interpreted as 02/07/2036.

I wonder, could this be fixed by always checking for noResponse?...

**Comment by TomsCircuits** [comment] 2018-10-27 14:52
I just found the following in RFC 958 / Network Time Protocol:

>    In some cases a particular timestamp may not be available, such as
>    when the protocol first starts up.  In these cases the 64-bit field
>    is set to zero, indicating the value is invalid or undefined.

So I'd say that even if you do get a response, a 0-timestamp can occur and needs to be handled.

**Comment by TomsCircuits** [comment] 2018-10-27 16:55
I left a modified version of the example from the lib running, and it seems I wasn't quite right. Here it goes wrong:

```
...
Server: 129.70.132.32 Secs: 3749646701 Got NTP time: 18:31:41 27/10/2018
Server: 129.70.132.32 Secs: 0 Got NTP time: 07:28:16 07/02/2036
Time Sync error: NTP server not reachable
Time set now to: 07:28:16 07/02/2036
Server: 129.70.132.32 Secs: 3749646728 Got NTP time: 18:32:08 27/10/2018
Server: 129.70.132.32 Secs: 3749646734 Got NTP time: 18:32:14 27/10/2018
...
```
But here it doesn't:

```
...
Server: 193.225.190.6 Secs: 3749644573 Got NTP time: 17:56:13 27/10/2018
Server: 193.225.190.6 Secs: 3749644579 Got NTP time: 17:56:19 27/10/2018
Time Sync error: NTP server not reachable
Time set now to: 17:56:19 27/10/2018
Server: 193.225.190.6 Secs: 3749644600 Got NTP time: 17:56:40 27/10/2018
Server: 193.225.190.6 Secs: 3749644606 Got NTP time: 17:56:46 27/10/2018
...
```
In the first example, the server sends a 0 timestamp and I get the year 2036 reading. In the second example, the server times out and the time remains intact. Perhaps it isn't that difficult to fix this thing after all.

**Comment by TomsCircuits** [comment] 2018-10-28 00:29
OK, I think I have a fix and I am currently testing it. It isn't easy, because I had no 0-timestamp over several hours.

**Comment by mcspr** [comment] 2018-10-28 02:55
@TomsCircuits You might have easier time testing with dummy server returning bad timestamp. 
For example, using python:
```python
import socket, struct
server = socket.socket(AF_INET, SOCK_DGRAM)
server.bind(('0.0.0.0', 12345)) # runs server on all addresses and uses port 12345
while True:
    data, addr = server.recvfrom(1024)
    print(data) # this can be unpacked using struct.unpack
    server.sendto(addr, data)
```
Just needs changing default port NtpClient uses (or run as privileged user to use 123)
Mirroring sent packet gives desired result of having 0 in the response and having 2036 as synced time. Or send whatever to see how client reacts.

About unpacking the data...
Referencing
https://tools.ietf.org/html/rfc5905#page-19
https://docs.python.org/3/library/struct.html#format-characters
it is probably this?
<s>`struct.unpack('H H 3I 4Q', data)`
4 timestamps in the end, 4 unsigned long longs (64bit)</s>
`struct.unpack('!H H 11I', data)` (*edit:* byte order. and might as well cut unused fraction part)

*edit:* Also see https://tools.ietf.org/html/rfc5905#page-76
> A kiss-o'-death packet is an NTP header with leap 0x3 (NOSYNC) and
    * stratum 16 (MAXSTRAT).  It tells the receiver that something
    * drastic has happened, as revealed by the kiss code in the refid
    * field.  The NTP header fields may or may not be correct.

**Comment by JosefKuchar** [comment] 2018-10-28 08:00
@TomsCircuits I have "better luck" with poor signal

**Comment by TomsCircuits** [comment] 2018-10-28 12:17
@mcspr 
Thanks for giving me a head-start. I kept my test running over night and didn't get a single sync error. Doh!
So it was a good idea to create a "fake" NTP server. I don't speak python, so it is probably no beauty. But it does the trick. Perhaps it is useful for others too, so here it is:

```
import socket, struct

server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server.bind(('0.0.0.0', 123)) # runs server on all addresses and uses port 123

base_time = 3749642240 # 17:17:20 27/10/2018
more_time = 0
error_cnt = 0

while True:
	#receive an NTP packet and unpack it
	data, addr = server.recvfrom(1024)
	B0, B1, B2, B3, T1, T1f, T2, T2f, T3, T3f, T4, T4f = struct.unpack('!12I', data)

	print "RX message:", hex(B0), B1, B2, hex(B3), T1, T1f, T2, T2f, T3, T3f, T4, T4f

	T4 = base_time + more_time # calculate new time
	more_time = more_time + 10
	
	error_cnt = error_cnt + 1 # create errors in a loop
	if error_cnt > 6:
		error_cnt = 0
		
	# set timestamp to invalid
	if error_cnt == 3:
		T4 = 0
	
	#repackage NTP data
	data = struct.pack('!12I', B0, B1, B2, B3, T1, T1f, T2, T2f, T3, T3f, T4, T4f)

	# send 5 out of 6 times
	if error_cnt < 6:
		B0, B1, B2, B3, T1, T1f, T2, T2f, T3, T3f, T4, T4f = struct.unpack('!12I', data)
		print "TX message:", hex(B0), B1, B2, hex(B3), T1, T1f, T2, T2f, T3, T3f, T4, T4f
		server.sendto(data, addr)
	print ""
```

And here is an example output showing received and transmitted data including errors (timestamp left zero in 3rd packet, no reply in 6th):

```
RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 3749642240 0

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 3749642250 0

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0 <<<<<<<<<<<<Timestamp is zero

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 3749642270 0

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 3749642280 0

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0 <<<<<<<<<<<< no response!

RX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 0 0
TX message: 0xe30006ecL 0 0 0x314e3134 0 0 0 0 0 0 3749642300 0
```

On the client side I get something like this:

```
Starting UDP
-- Receive NTP Response
Secs: 3749642240 
Summer Time
Sync frequency set low
Successful NTP sync at 17:17:20 27/10/2018
Got NTP time: 17:17:20 27/10/2018
Starting UDP
-- Receive NTP Response
Secs: 3749642250 
Summer Time
Sync frequency set low
Successful NTP sync at 17:17:30 27/10/2018
Got NTP time: 17:17:30 27/10/2018
Starting UDP
-- Receive NTP Response
Secs: 0            <<<<<<<<<<<<<<<<<<<<<<<<<< Timestamp is zero
--Timestamp is Zero
-- No valid NTP data :-(
Time Sync error: NTP server not reachable
Time is now: 17:17:42 27/10/2018  <<<<<<<<<<<<<< But the time is not 2036 anymore
Starting UDP
-- Receive NTP Response
Secs: 3749642270 
Summer Time
Sync frequency set low
Successful NTP sync at 17:17:50 27/10/2018
Got NTP time: 17:17:50 27/10/2018
Starting UDP
-- Receive NTP Response
Secs: 3749642280 
Summer Time
Sync frequency set low
Successful NTP sync at 17:18:00 27/10/2018
Got NTP time: 17:18:00 27/10/2018
Starting UDP
-- No NTP Response :-(          <<<<<<<<<<<<<<<<<<<<<< No response
Time Sync error: NTP server not reachable
Time is now: 17:18:13 27/10/2018        <<<<<<<<<<<<<<< as before: no corrupt time
Starting UDP
-- Receive NTP Response
Secs: 3749642300 
Summer Time
Sync frequency set low
Successful NTP sync at 17:18:20 27/10/2018
Got NTP time: 17:18:20 27/10/2018
```

**Comment by TomsCircuits** [comment] 2018-10-28 12:23
So, I think there is an improvement. It is perhaps not perfect. One problem is that apparently each time things like timezone, etc. are changed, the lib starts an extra sync. And if that goes wrong, then the false data will actually be used. In most applications, I am guessing that this is no real issue.

At least, in that case the sync interval goes back to short and so the wrong date will hopefully not be used for longer periods.

A side effect is that if the timestamp is wrong during startup, the time is now set to 1/1/1970.

**Comment by gmag11** [comment] 2019-01-04 19:41
Hi. I've had this project somehow stopped during a long time. Now, during some days I'm trying to evolve this lib to a more smart way to synchronize. I've included AsyncUDP version on develop branch. So, request is no more blocking while wainting for response. Please test it and check if there are any 2036 problem again.

**Comment by Defozo** [comment] 2019-03-28 17:30
Can we have a new release with this fix?

**Comment by bill-orange** [comment] 2019-04-01 19:20
I was not able to compile with the development version. I confess to not testing with the example.  My code was running with the release version.  When I tested with the development version, I got:

error: ambiguous overload for 'operator!=' (operand types are 'IPAddress' and 'int')

   
f (ipaddr != NULL && ntpServerIPAddress != 0)

                                              ^
What could I have done wrong?  I installed  ESPAsyncUDP-master to get this far.  I am using LwIP vers 2 (low memory) could that be it?

**Comment by gmag11** [comment] 2019-04-20 12:38
Please try latest version 3.0.0-beta

**Comment by gmag11** [comment] 2019-10-01 08:13
As there are no further comments I close this issue. Feel free to reopen it if required.

**Closed as completed by gmag11** 2019-10-01 08:13 UTC

**Comment by lightning003** [comment] 2019-11-04 12:28
The issue is still there with 3.1.0, Also I don't see any specific commits fixing this issue. Anyone still stuck on this?

**Comment by bill-orange** [comment] 2019-11-04 15:08
@lightning003 To the best of my knowledge the problem still exists, even in the betas.  I don’t think that the root of the problem lies in the library.  I think (based on no evidence whatsoever) that one sever in the pool is spitting out bad data.  If you happen to get it, you experience the problem.

Here’s what I did:

NTP.begin();
Serial.println("starting time sync");
NTP.setTimeZone (TIMEZONE);
while ((year(now()) < 1980) || (year(now()) > 2035)) {
    int i;
    delay (500);
    Serial.print("+");
    i++;
    if (i > 20) {
      Serial.println(); Serial.print("..................... no NTP time!");
      // you could reboot here if you wanted
    }
  }

Serial.println();
Serial.println(NTP.getTimeDateString())

The loop usually doesn’t go more than 3 iterations.

**Comment by lightning003** [comment] 2019-11-04 19:13
@bill-orange  ... yes I am also not able to force reproduce the scenario [hence del the comment], it occurred for me with other libraries as well and seems like they have same/similar issue, guess I will sync two times or verify with other ntp server to be sure - I don't see any other way,
Thanks for quick response, I will check your code as well - how it performs for me.

**Comment by dev-board-tech** [comment] 2024-07-09 10:45
So, after 7 years nothing has been done, I'm still getting 2036 most of the time from my SRM, even if the SRM UI show the correct time.
Some suggested to point my internal devices to time.nist, but IOT's are not belonging on the internet, they need a proxy to hide them from the internet.
